VERILOG = ../src/test68.v ../src/fx68k.v ../src/fx68kAlu.v ../src/uaddrPla.v \
          ../src/vram.v ../src/sdram.v ../src/hdmi.v ../src/ps2.v \
          ../src/sdram.v ../src/gamerom.v \
          ../src/osd/osd.v ../src/osd/spi_osd.v \
          ../src/osd/spi_ram_btn.v ../src/osd/spirw_slave_v.v \
	  ../src/ecp5pll.sv

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

