ACIAC	EQU $600001
ACIAD	EQU ACIAC+2
KEYROW1	EQU $600017

RDRF    EQU 0
TDRE    EQU 1

CR      EQU 13
LF      EQU 10
	ORG	$0000

	DC.L	$20000		; Set stack to top of RAM
	DC.L    START		; Set PC to start

START	BSR	INIT_ACIA
	MOVE.L	#$FFFF,D1
	DBRA	D1,$

LOOP	
	MOVE.B	KEYROW1.L,D0	; Get Keyrow 0
	BEQ.S	LOOP            ; Is key pressed?
	BTST.L	#1,D0
	BEQ.S	NOTLEFT
	LEA.L	LEFT.L,A0
	BSR.S	OUTL		; Output message
NOTLEFT
	BTST.L	#4,D0
	BEQ.S	NOTRIGHT
	LEA.L	RIGHT.L,A0
	BSR.S	OUTL		; Output message
NOTRIGHT
	BTST.L	#2,D0
	BEQ.S	NOTUP
	LEA.L	UP.L,A0
	BSR.S	OUTL		; Output message
NOTUP
	BTST.L	#7,D0
	BEQ.S	NOTDOWN
	LEA.L	DOWN.L,A0
	BSR.S	OUTL		; Output message
NOTDOWN
	BTST.L	#6,D0
	BEQ.S	NOTFIRE
	LEA.L	FIRE.L,A0
	BSR.S	OUTL		; Output message
NOTFIRE
	MOVE.W  #4,D2
NOTFIRE1
	MOVE.W	#$FFFF,D1	; Delay
	DBRA	D1,$
	DBRA	D2,NOTFIRE1
	BRA.S	LOOP

STOP	STOP    #$2700

UP	DC.B    "Up",CR,LF,0,0
DOWN	DC.B    "Down",CR,LF,0,0
LEFT	DC.B    "Left",CR,LF,0,0
RIGHT	DC.B    "Right",CR,LF,0
FIRE	DC.B    "Fire",CR,LF,0,0

OUTL    MOVE.B  (A0)+,D0
	BEQ.S   OUTL1
	BSR.S	OUTC
	BRA.S	OUTL
OUTL1	RTS

OUTC	BSR.S	COUT
	MOVE.W	#2000,D1
	DBRA D1,$
	RTS

INIT_ACIA  MOVE.B #3,ACIAC.L   ; RESET ACIA
           MOVE.W #10000,D0
           DBRA  D0,$
           MOVE.B #$15,ACIAC.L   ; rts enabled 9600 8ne
           RTS

COUT      BTST.B #TDRE,ACIAC.L
          BEQ.S  COUT
          MOVE.B D0,ACIAD.L
          RTS


CINS      BTST.B #RDRF,ACIAC.L
          BEQ.S  CINS
          MOVE.B ACIAD.L,D0
          RTS


CIN      BTST.B #RDRF,ACIAC.L
         BEQ.S  CIN
         MOVE.B ACIAD.L,D0
         BSR COUT
         RTS

